package client;

import entity.LogInfo;
import server.LogInHandler;

import javax.swing.*;
import java.awt.*;
import java.net.InetAddress;
import java.sql.SQLException;

public class LogInForm extends javax.swing.JFrame{
    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JButton Login;
    private javax.swing.JButton Register;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtUID;
    // End of variables declaration//GEN-END:variables

    /** Creates new form LogForm */
    public LogInForm() {
        initComponents();

        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.*/

    private void initComponents() {
        jPanel = new javax.swing.JPanel();
        jLabel0 = new javax.swing.JLabel();
        Font font=new Font("Times New Roman",Font.BOLD,20);
        jLabel0.setFont(font);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        txtUID = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel0.setText("Log in~");

        jLabel1.setText("Uid :");

        jLabel2.setText("Password :");



        Login.setText("Login");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });

        Register.setText("Register");
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(
                jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout
                .setHorizontalGroup(jPanelLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanelLayout
                                        .createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(
                                                jPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                jPanelLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel0,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                95,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                        )
                                                        .addGap(50, 50, 50)
                                                        .addGroup(
                                                                jPanelLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel2, //Password
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                95,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(
                                                                                password,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                286,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(
                                                                jPanelLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel1,  //Uid
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                86,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(
                                                                                txtUID,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                286,
                                                                                Short.MAX_VALUE)))
                                        .addGap(86, 86, 86))
                        .addGroup(
                                jPanelLayout.createSequentialGroup()
                                        .addGap(52, 52, 52).addComponent(Login)
                                        .addGap(98, 98, 98)
                                        .addComponent(Register)
                                        .addContainerGap(186, Short.MAX_VALUE)));
        jPanelLayout
                .setVerticalGroup(jPanelLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanelLayout
                                        .createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(
                                                jPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                jLabel0,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                36,
                                                                GroupLayout.DEFAULT_SIZE)
                                        )
                                        .addGap(56, 56, 56)
                                        .addGroup(
                                                jPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                jLabel1, //Uid
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                36,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                txtUID,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                31,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(56, 56, 56)
                                        .addGroup(
                                                jPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                jLabel2, //Password
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                42,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                password,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                34,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(
                                                jPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Login)
                                                        .addComponent(Register))
                                        .addGap(44, 44, 44)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jPanel,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup()
                        .addComponent(jPanel,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE)));

        pack();
    }

    private void LoginMouseClicked(java.awt.event.MouseEvent evt){
        // TODO add your handling code here:

        LogInfo loginfo = new LogInfo();
        loginfo.setPassword(new String(password.getPassword()));

        /***************setUid*******************/
        int uid = Integer.parseInt(txtUID.getText());
        loginfo.setUid(uid);
        System.out.println(uid);
        LogInHandler logInHandler = new LogInHandler();
        if(logInHandler.ConfirmInformation(loginfo) == true){
            JOptionPane.showMessageDialog(this,"Login success");

//            ChatBox chatBox = new ChatBox();
//            chatBox.setVisible(true);

            MainForm mainForm = new MainForm(uid);
            mainForm.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Login failed");
        }

    }
    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        RegForm regForm = new RegForm();
        regForm.setVisible(true);
    }


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }
}
